version = 0.1

[default]

# La phase 'package' upload le CODE PYTHON
[default.package]
[default.package.parameters]
s3_bucket = "covcov-造env造"
s3_prefix = "cognito"

# La phase 'package' upload le template
[default.deploy]
[default.deploy.parameters]
s3_bucket = "covcov-造env造"
s3_prefix = "template-cognito"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
